package pokemon

var AllPokemon = PokemonMap{
	1: {
		ID:         1,
		Name:       "Bulbasaur",
		Obtainable: true,
	},
	2: {
		ID:         2,
		Name:       "Ivysaur",
		Obtainable: true,
		Requires:   []PokemonID{1},
	},
	3: {
		ID:         3,
		Name:       "Venusaur",
		Obtainable: true,
		Requires:   []PokemonID{2},
	},
	4: {
		ID:         4,
		Name:       "Charmander",
		Obtainable: true,
	},
	5: {
		ID:         5,
		Name:       "Charmeleon",
		Obtainable: true,
		Requires:   []PokemonID{4},
	},
	6: {
		ID:         6,
		Name:       "Charizard",
		Obtainable: true,
		Requires:   []PokemonID{5},
	},
	7: {
		ID:         7,
		Name:       "Squirtle",
		Obtainable: true,
	},
	8: {
		ID:         8,
		Name:       "Wartortle",
		Obtainable: true,
		Requires:   []PokemonID{7},
	},
	9: {
		ID:         9,
		Name:       "Blastoise",
		Obtainable: true,
		Requires:   []PokemonID{8},
	},
	10: {
		ID:         10,
		Name:       "Caterpie",
		Obtainable: true,
		PreBrock:   true,
	},
	11: {
		ID:         11,
		Name:       "Metapod",
		Obtainable: true,
		PreBrock:   true,
	},
	12: {
		ID:         12,
		Name:       "Butterfree",
		Obtainable: true,
		Requires:   []PokemonID{11},
	},
	13: {
		ID:         13,
		Name:       "Weedle",
		Obtainable: true,
		PreBrock:   true,
	},
	14: {
		ID:         14,
		Name:       "Kakuna",
		Obtainable: true,
		PreBrock:   true,
	},
	15: {
		ID:         15,
		Name:       "Beedrill",
		Obtainable: true,
		Requires:   []PokemonID{14},
	},
	16: {
		ID:         16,
		Name:       "Pidgey",
		Obtainable: true,
		PreBrock:   true,
	},
	17: {
		ID:         17,
		Name:       "Pidgeotto",
		Obtainable: true,
	},
	18: {
		ID:         18,
		Name:       "Pidgeot",
		Obtainable: true,
		Requires:   []PokemonID{17},
	},
	19: {
		ID:         19,
		Name:       "Rattata",
		Obtainable: true,
		PreBrock:   true,
	},
	20: {
		ID:         20,
		Name:       "Raticate",
		Obtainable: true,
	},
	21: {
		ID:         21,
		Name:       "Spearow",
		Obtainable: true,
		PreBrock:   true,
	},
	22: {
		ID:         22,
		Name:       "Fearow",
		Obtainable: true,
	},
	23: {
		ID:         23,
		Name:       "Ekans",
		Obtainable: false,
	},
	24: {
		ID:         24,
		Name:       "Arbok",
		Obtainable: false,
	},
	25: {
		ID:         25,
		Name:       "Pikachu",
		Obtainable: true,
		// Pikachu is not Pre-Brock to prevent odd cases with converting to Eevee
	},
	26: {
		ID:         26,
		Name:       "Raichu",
		Obtainable: true,
		Requires:   []PokemonID{25},
	},
	27: {
		ID:         27,
		Name:       "Sandshrew",
		Obtainable: true,
	},
	28: {
		ID:         28,
		Name:       "Sandslash",
		Obtainable: true,
		Requires:   []PokemonID{27},
	},
	29: {
		ID:         29,
		Name:       "NidoranF",
		Obtainable: true,
		PreBrock:   true,
	},
	30: {
		ID:         30,
		Name:       "Nidorina",
		Obtainable: true,
	},
	31: {
		ID:         31,
		Name:       "Nidoqueen",
		Obtainable: true,
		Requires:   []PokemonID{30},
	},
	32: {
		ID:         32,
		Name:       "NidoranM",
		Obtainable: true,
		PreBrock:   true,
	},
	33: {
		ID:         33,
		Name:       "Nidorino",
		Obtainable: true,
	},
	34: {
		ID:         34,
		Name:       "Nidoking",
		Obtainable: true,
		Requires:   []PokemonID{33},
	},
	35: {
		ID:         35,
		Name:       "Clefairy",
		Obtainable: true,
	},
	36: {
		ID:             36,
		Name:           "Clefable",
		Obtainable:     true,
		OnePct:         true,
		OnePctRequires: []PokemonID{35},
	},
	37: {
		ID:         37,
		Name:       "Vulpix",
		Obtainable: false,
	},
	38: {
		ID:         38,
		Name:       "Ninetales",
		Obtainable: false,
	},
	39: {
		ID:         39,
		Name:       "Jigglypuff",
		Obtainable: true,
	},
	40: {
		ID:         40,
		Name:       "Wigglytuff",
		Obtainable: true,
		Requires:   []PokemonID{39},
	},
	41: {
		ID:         41,
		Name:       "Zubat",
		Obtainable: true,
	},
	42: {
		ID:         42,
		Name:       "Golbat",
		Obtainable: true,
	},
	43: {
		ID:         43,
		Name:       "Oddish",
		Obtainable: true,
		PreBrock:   true,
	},
	44: {
		ID:         44,
		Name:       "Gloom",
		Obtainable: true,
	},
	45: {
		ID:             45,
		Name:           "Vileplume",
		Obtainable:     true,
		OnePct:         true,
		OnePctRequires: []PokemonID{44},
	},
	46: {
		ID:         46,
		Name:       "Paras",
		Obtainable: true,
	},
	47: {
		ID:         47,
		Name:       "Parasect",
		Obtainable: true,
		Requires:   []PokemonID{46},
	},
	48: {
		ID:         48,
		Name:       "Venonat",
		Obtainable: true,
	},
	49: {
		ID:         49,
		Name:       "Venomoth",
		Obtainable: true,
	},
	50: {
		ID:         50,
		Name:       "Diglett",
		Obtainable: true,
	},
	51: {
		ID:         51,
		Name:       "Dugtrio",
		Obtainable: true,
	},
	52: {
		ID:         52,
		Name:       "Meowth",
		Obtainable: false,
	},
	53: {
		ID:         53,
		Name:       "Persian",
		Obtainable: true,
		Requires:   []PokemonID{58},
	},
	54: {
		ID:         54,
		Name:       "Psyduck",
		Obtainable: true,
	},
	55: {
		ID:         55,
		Name:       "Golduck",
		Obtainable: true,
		Requires:   []PokemonID{54},
	},
	56: {
		ID:         56,
		Name:       "Mankey",
		Obtainable: true,
	},
	57: {
		ID:         57,
		Name:       "Primeape",
		Obtainable: true,
		Requires:   []PokemonID{56},
	},
	58: {
		ID:         58,
		Name:       "Growlithe",
		Obtainable: true,
	},
	59: {
		ID:         59,
		Name:       "Arcanine",
		Obtainable: true,
		Requires:   []PokemonID{58},
	},
	60: {
		ID:         60,
		Name:       "Poliwag",
		Obtainable: true,
	},
	61: {
		ID:         61,
		Name:       "Poliwhirl",
		Obtainable: true,
	},
	62: {
		ID:         62,
		Name:       "Poliwrath",
		Obtainable: true,
		Requires:   []PokemonID{61},
	},
	63: {
		ID:         63,
		Name:       "Abra",
		Obtainable: true,
	},
	64: {
		ID:             64,
		Name:           "Kadabra",
		Obtainable:     true,
		OnePct:         true,
		OnePctRequires: []PokemonID{63},
	},
	65: {
		ID:         65,
		Name:       "Alakazam",
		Obtainable: false,
	},
	66: {
		ID:         66,
		Name:       "Machop",
		Obtainable: true,
	},
	67: {
		ID:         67,
		Name:       "Machoke",
		Obtainable: true,
		Requires:   []PokemonID{66},
	},
	68: {
		ID:         68,
		Name:       "Machamp",
		Obtainable: false,
	},
	69: {
		ID:         69,
		Name:       "Bellsprout",
		Obtainable: false,
	},
	70: {
		ID:         70,
		Name:       "Weepinbell",
		Obtainable: false,
	},
	71: {
		ID:         71,
		Name:       "Victreebel",
		Obtainable: false,
	},
	72: {
		ID:         72,
		Name:       "Tentacool",
		Obtainable: true,
	},
	73: {
		ID:         73,
		Name:       "Tentacruel",
		Obtainable: true,
	},
	74: {
		ID:         74,
		Name:       "Geodude",
		Obtainable: true,
	},
	75: {
		ID:         75,
		Name:       "Graveler",
		Obtainable: true,
	},
	76: {
		ID:         76,
		Name:       "Golem",
		Obtainable: false,
	},
	77: {
		ID:         77,
		Name:       "Ponyta",
		Obtainable: true,
	},
	78: {
		ID:         78,
		Name:       "Rapidash",
		Obtainable: true,
	},
	79: {
		ID:         79,
		Name:       "Slowpoke",
		Obtainable: true,
	},
	80: {
		ID:         80,
		Name:       "Slowbro",
		Obtainable: true,
	},
	81: {
		ID:         81,
		Name:       "Magnemite",
		Obtainable: true,
	},
	82: {
		ID:         82,
		Name:       "Magneton",
		Obtainable: true,
	},
	83: {
		ID:         83,
		Name:       "Farfetch'd",
		Obtainable: true,
	},
	84: {
		ID:         84,
		Name:       "Doduo",
		Obtainable: true,
	},
	85: {
		ID:         85,
		Name:       "Dodrio",
		Obtainable: true,
	},
	86: {
		ID:         86,
		Name:       "Seel",
		Obtainable: true,
	},
	87: {
		ID:         87,
		Name:       "Dewgong",
		Obtainable: true,
	},
	88: {
		ID:         88,
		Name:       "Grimer",
		Obtainable: true,
	},
	89: {
		ID:         89,
		Name:       "Muk",
		Obtainable: true,
	},
	90: {
		ID:         90,
		Name:       "Shellder",
		Obtainable: true,
	},
	91: {
		ID:             91,
		Name:           "Cloyster",
		Obtainable:     true,
		OnePct:         true,
		OnePctRequires: []PokemonID{90},
	},
	92: {
		ID:         92,
		Name:       "Gastly",
		Obtainable: true,
	},
	93: {
		ID:         93,
		Name:       "Haunter",
		Obtainable: true,
	},
	94: {
		ID:         94,
		Name:       "Gengar",
		Obtainable: false,
	},
	95: {
		ID:         95,
		Name:       "Onix",
		Obtainable: true,
	},
	96: {
		ID:         96,
		Name:       "Drowzee",
		Obtainable: true,
	},
	97: {
		ID:         97,
		Name:       "Hypno",
		Obtainable: true,
		Requires:   []PokemonID{96},
	},
	98: {
		ID:         98,
		Name:       "Krabby",
		Obtainable: true,
	},
	99: {
		ID:         99,
		Name:       "Kingler",
		Obtainable: true,
	},
	100: {
		ID:         100,
		Name:       "Voltorb",
		Obtainable: true,
	},
	101: {
		ID:         101,
		Name:       "Electrode",
		Obtainable: true,
	},
	102: {
		ID:         102,
		Name:       "Exeggcute",
		Obtainable: false,
	},
	103: {
		ID:         103,
		Name:       "Exeggutor",
		Obtainable: false,
	},
	104: {
		ID:         104,
		Name:       "Cubone",
		Obtainable: true,
	},
	105: {
		ID:         105,
		Name:       "Marowak",
		Obtainable: true,
		Requires:   []PokemonID{104},
	},
	106: {
		ID:         106,
		Name:       "Hitmonlee",
		Obtainable: true,
		Excludes:   []PokemonID{107},
	},
	107: {
		ID:         107,
		Name:       "Hitmonchan",
		Obtainable: true,
		Excludes:   []PokemonID{106},
	},
	108: {
		ID:         108,
		Name:       "Lickitung",
		Obtainable: false,
	},
	109: {
		ID:         109,
		Name:       "Koffing",
		Obtainable: false,
	},
	110: {
		ID:         110,
		Name:       "Weezing",
		Obtainable: false,
	},
	111: {
		ID:         111,
		Name:       "Rhyhorn",
		Obtainable: true,
	},
	112: {
		ID:         112,
		Name:       "Rhydon",
		Obtainable: true,
		Requires:   []PokemonID{111},
	},
	113: {
		ID:         113,
		Name:       "Chansey",
		Obtainable: true,
	},
	114: {
		ID:         114,
		Name:       "Tangela",
		Obtainable: true,
	},
	115: {
		ID:             115,
		Name:           "Kangaskhan",
		Obtainable:     true,
		OnePct:         true,
		OnePctRequires: []PokemonID{-1},
	},
	116: {
		ID:         116,
		Name:       "Horsea",
		Obtainable: true,
	},
	117: {
		ID:         117,
		Name:       "Seadra",
		Obtainable: true,
	},
	118: {
		ID:         118,
		Name:       "Goldeen",
		Obtainable: true,
	},
	119: {
		ID:         119,
		Name:       "Seaking",
		Obtainable: true,
	},
	120: {
		ID:         120,
		Name:       "Staryu",
		Obtainable: true,
	},
	121: {
		ID:             121,
		Name:           "Starmie",
		Obtainable:     true,
		OnePct:         true,
		OnePctRequires: []PokemonID{120},
	},
	122: {
		ID:         122,
		Name:       "Mr. Mime",
		Obtainable: true,
	},
	123: {
		ID:             123,
		Name:           "Scyther",
		Obtainable:     true,
		OnePct:         true,
		OnePctRequires: []PokemonID{-1},
	},
	124: {
		ID:         124,
		Name:       "Jynx",
		Obtainable: true,
	},
	125: {
		ID:         125,
		Name:       "Electabuzz",
		Obtainable: true,
	},
	126: {
		ID:         126,
		Name:       "Magmar",
		Obtainable: true,
	},
	127: {
		ID:         127,
		Name:       "Pinsir",
		Obtainable: false,
	},
	128: {
		ID:         128,
		Name:       "Tauros",
		Obtainable: true,
	},
	129: {
		ID:         129,
		Name:       "Magikarp",
		Obtainable: true,
	},
	130: {
		ID:         130,
		Name:       "Gyarados",
		Obtainable: true,
	},
	131: {
		ID:         131,
		Name:       "Lapras",
		Obtainable: true,
	},
	132: {
		ID:         132,
		Name:       "Ditto",
		Obtainable: true,
	},
	133: {
		ID:         133,
		Name:       "Eevee",
		Obtainable: true,
	},
	134: {
		ID:         134,
		Name:       "Vaporeon",
		Obtainable: true,
		Requires:   []PokemonID{135},
	},
	135: {
		ID:         135,
		Name:       "Jolteon",
		Obtainable: true,
		Requires:   []PokemonID{133},
	},
	136: {
		ID:         136,
		Name:       "Flareon",
		Obtainable: true,
		Requires:   []PokemonID{135},
	},
	137: {
		ID:         137,
		Name:       "Porygon",
		Obtainable: true,
	},
	138: {
		ID:         138,
		Name:       "Omanyte",
		Obtainable: true,
		Excludes:   []PokemonID{140},
	},
	139: {
		ID:         139,
		Name:       "Omastar",
		Obtainable: true,
		Requires:   []PokemonID{138},
	},
	140: {
		ID:         140,
		Name:       "Kabuto",
		Obtainable: true,
		Excludes:   []PokemonID{138},
	},
	141: {
		ID:         141,
		Name:       "Kabutops",
		Obtainable: true,
		Requires:   []PokemonID{140},
	},
	142: {
		ID:         142,
		Name:       "Aerodactyl",
		Obtainable: true,
	},
	143: {
		ID:         143,
		Name:       "Snorlax",
		Obtainable: true,
	},
	144: {
		ID:         144,
		Name:       "Articuno",
		Obtainable: true,
	},
	145: {
		ID:         145,
		Name:       "Zapdos",
		Obtainable: true,
	},
	146: {
		ID:         146,
		Name:       "Moltres",
		Obtainable: false,
	},
	147: {
		ID:             147,
		Name:           "Dratini",
		Obtainable:     true,
		OnePct:         true,
		OnePctRequires: []PokemonID{-1},
	},
	148: {
		ID:             148,
		Name:           "Dragonair",
		Obtainable:     true,
		OnePct:         true,
		OnePctRequires: []PokemonID{147},
	},
	149: {
		ID:         149,
		Name:       "Dragonite",
		Obtainable: true,
		Requires:   []PokemonID{148},
	},
	150: {
		ID:         150,
		Name:       "Mewtwo",
		Obtainable: false,
	},
}
